/* Generated by build/emit.py from the uploaded guide + IBA 2024 list. Do not edit by hand. */

export const INGREDIENTS = {
  "gin": { "abv": 40.0, "cat": "spirit", "col": "#dfe9f0", "name": "London Dry Gin" },
  "old tom gin": { "abv": 42.0, "cat": "spirit", "col": "#e6dcc0", "name": "Old Tom Gin" },
  "vodka": { "abv": 40.0, "cat": "spirit", "col": "#eaf1f6", "name": "Vodka" },
  "citron vodka": { "abv": 40.0, "cat": "spirit", "col": "#f2f4c8", "name": "Citron Vodka" },
  "vanilla vodka": { "abv": 40.0, "cat": "spirit", "col": "#f3e6c4", "name": "Vanilla Vodka" },
  "rum white": { "abv": 40.0, "cat": "spirit", "col": "#f4f1e6", "name": "White Rum" },
  "rum gold": { "abv": 40.0, "cat": "spirit", "col": "#e0a94a", "name": "Gold Rum" },
  "rum dark": { "abv": 40.0, "cat": "spirit", "col": "#7a4419", "name": "Jamaican Dark Rum" },
  "rum overproof": { "abv": 75.5, "cat": "spirit", "col": "#efe6cf", "name": "Overproof Rum (151)" },
  "cachaça": { "abv": 42.0, "cat": "spirit", "col": "#f2efdf", "name": "Cachaça" },
  "tequila blanco": { "abv": 40.0, "cat": "spirit", "col": "#f4f2e2", "name": "Tequila Blanco" },
  "tequila reposado": { "abv": 40.0, "cat": "spirit", "col": "#eedfa8", "name": "Tequila Reposado" },
  "mezcal": { "abv": 45.0, "cat": "spirit", "col": "#efe6c8", "name": "Mezcal Espadín" },
  "whiskey bourbon": { "abv": 45.0, "cat": "spirit", "col": "#c4762a", "name": "Bourbon Whiskey" },
  "whiskey rye": { "abv": 47.0, "cat": "spirit", "col": "#c98a34", "name": "Rye Whiskey" },
  "whiskey irish": { "abv": 40.0, "cat": "spirit", "col": "#d9a44a", "name": "Irish Whiskey" },
  "scotch blended": { "abv": 40.0, "cat": "spirit", "col": "#d5973c", "name": "Blended Scotch Whisky" },
  "scotch islay": { "abv": 46.0, "cat": "spirit", "col": "#c8873a", "name": "Islay Single Malt" },
  "cognac": { "abv": 40.0, "cat": "spirit", "col": "#b5651d", "name": "Cognac" },
  "brandy": { "abv": 40.0, "cat": "spirit", "col": "#b5651d", "name": "Brandy" },
  "calvados": { "abv": 40.0, "cat": "spirit", "col": "#d9b25e", "name": "Calvados" },
  "pisco": { "abv": 42.0, "cat": "spirit", "col": "#f3efd9", "name": "Pisco" },
  "grappa": { "abv": 45.0, "cat": "spirit", "col": "#f1eedd", "name": "Grappa" },
  "vermouth dry": { "abv": 18.0, "cat": "fortified", "col": "#f0e9c0", "name": "Dry Vermouth" },
  "vermouth sweet": { "abv": 16.0, "cat": "fortified", "col": "#8e2f22", "name": "Sweet Red Vermouth" },
  "lillet blanc": { "abv": 17.0, "cat": "fortified", "col": "#f0e2a8", "name": "Lillet Blanc" }
};

export const BOSS_ROSTER = [
  "dry-martini",
  "vesper",
  "martinez",
  "casino",
  "tuxedo",
  "hanky-panky",
  "bijou",
  "espresso-martini",
  "french-martini",
  "lemon-drop-martini",
  "appletini",
  "porn-star-martini",
  "corpse-reviver-2",
  "cardinale",
  "remember-the-maine"
];

export const RECIPES = [
  {
    "id": "alexander",
    "name": "Alexander",
    "printedAs": null,
    "cat": "unforgettables",
    "src": "guide",
    "conf": "med",
    "flag": "Source prints \" Fresh Fresh Cream \" (duplication typo). Read as fresh cream.",
    "glass": "coupe",
    "icePrep": "cubes",
    "iceServe": "none",
    "vessel": "shaker",
    "strain": "fine",
    "tech": [
      { "t": "shake", "s": 12 }
    ],
    "garnish": "Freshly grated nutmeg",
    "ings": [
      { "k": "gin", "q": 30.0, "u": "ml", "l": "Beefeater London Dry Gin", "ml": 30.0, "abv": 40.0 },
      { "k": "crème de cacao dark", "q": 30.0, "u": "ml", "l": "Dark Creme de Cacao", "ml": 30.0, "abv": 24.0 },
      { "k": "cream", "q": 30.0, "u": "ml", "l": "Fresh Fresh Cream", "ml": 30.0, "abv": 0 }
    ],
    "method": "Shake all ingredients vigorously with fresh ice for 12 seconds. Fine strain into a chilled coupe or cocktail glass. Dust the top with freshly grated nutmeg.",
    "family": "shaken",
    "abv": {
      "absolute_ml": 19.2,
      "absolute_g": 15.15,
      "volume_pre_ml": 90.0,
      "volume_served_ml": 109.8,
      "abv_pre": 21.33,
      "abv_served": 17.49,
      "dilution_pct": 22.0,
      "std_au": 1.52,
      "std_us": 1.08,
      "has_top": false
    },
    "story": "The Brandy Alexander descends from the gin Alexander, itself named for Queen Alexandra. The cognac version was already the fashionable London after-dinner drink by the 1920s and was immortalised in Noël Coward's 1928 song 'The Young People', where the young couple are 'lapped in a warm and fuzzy embrace' by 'a Brandy Alexander'.",
    "taste": "Cocoa and vanilla up front, soft cognac warmth underneath, cream rounding off the finish. Dessert-like; nutmeg on the nose is doing real work, not decoration.",
    "myth": "Often credited to Alexander the Great or to a specific royal event; there is no evidence for either. The name simply follows the Edwardian habit of naming drinks after Alexandra."
  }
];

export const BUILD = {
  "guideRecipes": 93,
  "ibaAdded": 26,
  "total": 119,
  "boss": 15
};
